services:
  - type: web
    name: xtreamcodes
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /data
      - key: PORT
        value: 10000
      - key: TRUST_PROXY
        value: 1
      - key: DISABLE_CLUSTER
        value: true
      - key: SEED_WHITELIST_IPS
        value: 78.190.61.131
      - key: GITHUB_BACKUP_REPO
        value: steamixtvlive/steamix-ultimate-ui-panel
      - key: GITHUB_BACKUP_BRANCH
        value: backups
      - key: GITHUB_BACKUP_INTERVAL_MIN
        value: 60
